### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Add continuous integration with Github Actions
- [x] Add compatibility with Symfony 5
- [x] Remove composer.lock file
- [x] Normalize the composer.json file
- [x] Add missing static files (_editorconfig, grumphp,..._)
- [x] Update code style
- [x] Fix tests
- [x] Fix "`OCI_SUCCESS_WITH_INFO: ORA-28002: the password will expire within 7 days`"

Tests are passing: https://github.com/drupol/doctrine-oci8-extended/actions/runs/80185804

### CODE REVIEW

**Comment by jasonhofer** [comment]
Thank you, but I'm going to decline your pull request.

**Comment by drupol** [comment]
Ok, 

Nothing else ? Not any explanation words ?

**Comment by jasonhofer** [comment]
@drupol this PR hijacks over 1300 lines of code, giving the false impression that you authored over 40% of this project. The vast majority of these changes are just rearranging and reformatting lines of code. Shame on you.

**Comment by drupol** [comment]
Fair enough ! Thanks.

**Comment by jasonhofer** [comment]
Uh... why did a plethora of open source all-stars show up out of nowhere and thumbs down my comment? @drupol , do you know anything about that? I'm a total nobody here in githubland, so if I've committed some kind of open source community sin, I will need that to be explained to me, for I have been sufficiently humbled.

@drupol, my first impression was that you obviously have friends in high places, and so you must have ordered a hit on me, like something out of The Godfather... "@drupol, @drupol. We can't remember the last time that you invited us to your house for a cup of coffee. But uh, now you come to us and you say '_Don @jwage, Don @Ocramius, give me justice_'"

So, here I am, an absolute, random nobody, and my silly reason for rejecting some random (to me) dude's PR gets 47 thumbs down, a number of which are from names I've respected for over a decade now... I am baffled, and I obviously need to be "got schooled" about something that I missed, so someone lay it on me, please.

**Comment by drupol** [comment]
After your last reply, I was kinda surprised. I think it's the first time I received such a reply for a contribution to an open source project, as "_bad_" as the contribution can be.
But it's been years that I'm in OpenSource, and things like that happens, we cannot be always in a good mood, I accept it.

I do agree that my PR is huge and there is a context to this story.

I work at European Commission and I've been asked to evaluate "_your_" package. While doing it, I usually commits stuff in temporary branches, stuff that I would have done in a different ways. Some of them are opinionated, some of them aren't.
Then, usually I consolidate one PR and each commits are properly separated, so we can discuss what to accept or reject.

Now, I don't have "_friends in high places_", I just have "_colleagues_" that are working with open source everyday, and we are a respectable community of people, brain and resources.
We are aware that we cannot be equal when it comes to PHP knowledge, but everyone is trying to learn "_from the shoulders of the giants_" every day, and those giants usually take the time to explain when something is right or wrong.
It usually helps to raise the average people's PHP knowledge in the community, for the greater good of everyone.

I posted [this thread on Twitter](https://twitter.com/drupol/status/1311170617148874759) and I got a lot of feedback. You see, after years, there are still things to learn! This is also most probably why you received so much attention and "_stars_" in this thread.

> I spent my life trying not to be careless -- women and children can be careless, but not men. --Corleone

With this PR, I didn't meant to offend your work or trying to acquire half of the code attribution. We are on Github, and it's here to keep a history of the changes, so, no, I wasn't trying to hijack your work, this is not my mindset and I'm sorry for you that you felt that way.

As this project needs maintenance (_Symfony 5 support_), I'm in the process of evaluating if a fork would a better solution.

**Comment by jasonhofer** [comment]
Thank you for your reply, and for sharing that Twitter thread. I meant no disrespect, and I agree that I probably should have offered suggestions. I dont have much spare time, though.

I also dont have very much code "out there" for the public, and I use this **one** project that I actually did put out there to showcase my coding ability to prospective employers. I don't want them to have to dig through commits to find my name. It doesn't seem like this little project of mine has gained enough traction for me to emotionally "let it go". It's still more important and useful to me than it is to the community. When and if that changes, I will have no problem with accepting the fact that the code is no longer "mine".

I do have an interest in some of the changes you made. But they were buried in all the reformatting changes. If you can make small discreet PRs, each focused on one particular change, I will reevaluate and will likely merge them.

I do need help implementing semantic versioning, if you have experience, or know of a good resource that explains how to do it, that would be appreciated.

And please Tweet this so the Internet can go back to feeling neutral toward, and uninterested in, me.

**Comment by drupol** [comment]
So glad to read this!

Get ready to receive some Github notifications very soon :-)

**Comment by drupol** [comment]
Dear @jasonhofer,

I finally created multiple draft PRs from this huge PR.

I took care to not include any CI and code style changes, if you wish to reconsider those changes, it will be possible to do it at a later time.

Now, let's use those new PRs as base and continue our discussions in there.

Ok ?

**Pull request closed without merging**
